### ISSUE TITLE
VSCode 安装好 jieba 插件之后，会影响英文下的分词 (下划线 _ )

### ISSUE THREAD

**Issue by yuhuangmeng** [stephanoskomnenos/vscode-jieba#43]
## 问题描述

原来下划线左右如果不是空白，是不会当作一个 “分词” 来划分的，比如 `a_b_c` 整体是一个分词，`a _b` 是两个分词，`a_ b` 是两个分词，`a _ b` 是三个分词。但安装 jieba 之后，`a_b`, `a _b`, `a_ b` 都是三个分词。

## 期望结果

`a_b` 是一个分词，`a _b`, `a_ b` 都是两个分词。

## 实际结果

`a_b`, `a _b`, `a_ b` 都是三个分词。

## 功能完善

可以提供一个设置选项，让 `_` 不再是一个单独的分词（除非左右都是空白），而是跟其他字母一起的一个分词。

**Comment by stephanoskomnenos** [comment]
新版本已修复
